# Generated by Django 5.0 on 2024-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_component_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(verbose_name=25)),
                ('fuel', models.CharField(verbose_name=25)),
                ('co2_factor', models.FloatField()),
                ('primary_energy_factor', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.UniqueConstraint(fields=('country', 'fuel'), name='composite_pk'),
        ),
    ]
