# Generated by Django 5.0 on 2024-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_wall_or_insulation_type_wall_insulation_materials_wall_or_insulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='SHEET_TYPE',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_subtype',
            field=models.CharField(db_column='subtype', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(db_column='type', max_length=250),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='component',
            name='replace_or_die',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='factor',
            name='country',
            field=models.CharField(verbose_name=250),
        ),
        migrations.AlterField(
            model_name='factor',
            name='fuel',
            field=models.CharField(verbose_name=250),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='project_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='wall_insulation_materials',
            name='component_element',
            field=models.CharField(verbose_name=250),
        ),
        migrations.AlterField(
            model_name='wall_insulation_materials',
            name='wall_or_insulation',
            field=models.CharField(verbose_name=250),
        ),
    ]
