# Generated by Django 5.0 on 2024-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_component_sheet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulation_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=250)),
                ('conductivity', models.FloatField()),
                ('capacity', models.FloatField()),
                ('density', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Wall_Insulation_Materials',
        ),
    ]
