# Generated by Django 5.0 on 2024-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_insulation_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insulation_materials',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
