# Generated by Django 5.0 on 2024-03-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_insulation_materials_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insulation_Materials',
            new_name='Wall_Materials',
        ),
    ]
