# Generated by Django 5.0 on 2024-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_insulation_materials_wall_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='thermal_properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
