# Generated by Django 5.0 on 2024-03-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='co2_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='primary_energy_factor',
            field=models.FloatField(null=True),
        ),
    ]
