# Generated by Django 5.0 on 2024-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_factor_co2_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='bibliography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
