# Generated by Django 5.0 on 2024-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_component_is_b_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='IS_B_COMPONENT',
            field=models.BooleanField(),
        ),
    ]
