# Generated by Django 5.0 on 2024-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_component_is_b_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarbonIntensityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('zone_name', models.CharField(max_length=255)),
                ('zone_id', models.CharField(max_length=100)),
                ('carbon_intensity_gco2_eq_kwh_direct', models.FloatField()),
                ('carbon_intensity_gco2_eq_kwh_lca', models.FloatField()),
                ('low_carbon_percentage', models.FloatField()),
                ('renewable_percentage', models.FloatField()),
                ('data_source', models.CharField(max_length=255)),
                ('data_estimated', models.BooleanField()),
                ('data_estimation_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'datetime'], name='inventory_c_country_b3be05_idx')],
                'unique_together': {('country', 'datetime')},
            },
        ),
    ]
