# Generated by Django 5.0 on 2024-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_component_is_b_component'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='factor',
            name='composite_pk',
        ),
        migrations.AddField(
            model_name='factor',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.UniqueConstraint(fields=('country', 'fuel', 'year'), name='composite_pk'),
        ),
    ]
