# Generated by Django 5.0 on 2024-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_component_eol_co2_cost_component_eol_pe_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonintensitydata',
            name='data_estimated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
