# Generated by Django 5.0 on 2024-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_carbonintensitydata_data_estimated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorElectricityYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(verbose_name=250)),
                ('year', models.IntegerField()),
                ('measurement_co2', models.FloatField()),
                ('source', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='factorelectricityyear',
            constraint=models.UniqueConstraint(fields=('country', 'measurement_co2'), name='composite_pk_2'),
        ),
    ]
