# Generated by Django 5.0 on 2024-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_factorelectricityyear_composite_pk_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='functional_unit',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='ia_method_ghg',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='ia_method_pe',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='lca_db',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='simapro_version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
