# Generated by Django 5.0 on 2024-10-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_loggingcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('embodied_primary_energy', models.FloatField()),
                ('embodied_co2', models.FloatField()),
                ('functional_unit', models.CharField(verbose_name=250)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
            ],
        ),
    ]
