# Generated by Django 5.0 on 2024-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_regressionvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regressionvalues',
            name='functional_unit',
            field=models.TextField(),
        ),
    ]
