# Generated by Django 5.0 on 2024-10-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_regressionvalues_functional_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimaPro_runs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fu_quantity', models.FloatField()),
                ('fu_measurement_unit', models.TextField()),
                ('stage_A_gwp_kgco2eq', models.FloatField()),
                ('stage_A_embodied_pe_gj', models.FloatField()),
                ('stage_A_LCA_version', models.TextField()),
                ('stage_A_IA_method_GWP', models.TextField()),
                ('stage_A_IA_method_PE', models.TextField()),
                ('stage_A_comments', models.TextField()),
                ('eol_gwp_pc', models.FloatField()),
                ('eol_embodied_pe_pc', models.FloatField()),
                ('waste_treatment', models.TextField()),
                ('stage_C_LCA_version', models.TextField()),
                ('stage_C_IA_method_GWP', models.TextField()),
                ('stage_C_IA_method_PE', models.TextField()),
                ('stage_C_comments', models.TextField()),
                ('general_comments', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sheet_type', models.CharField(verbose_name=250)),
                ('is_main_inventory', models.BooleanField()),
                ('vcomponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.component')),
            ],
        ),
    ]
