# Generated by Django 5.0 on 2024-10-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_simapro_runs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simapro_runs',
            old_name='is_main_inventory',
            new_name='IS_MAIN_INVENTORY',
        ),
        migrations.RenameField(
            model_name='simapro_runs',
            old_name='sheet_type',
            new_name='SHEET_TYPE',
        ),
        migrations.AddField(
            model_name='simapro_runs',
            name='component_subtype',
            field=models.CharField(db_column='subtype', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simapro_runs',
            name='component_type',
            field=models.CharField(db_column='type', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
