# Generated by Django 5.0 on 2024-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_is_main_inventory_simapro_runs_is_main_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='SHEET_TYPE',
            field=models.CharField(max_length=100),
        ),
    ]
