# Generated by Django 5.0 on 2024-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_simapro_runs_sheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='IS_MAIN_INVENTORY',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='SHEET_TYPE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='component_type',
            field=models.CharField(db_column='type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='general_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_IA_method_GWP',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_IA_method_PE',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_LCA_version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_IA_method_GWP',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_IA_method_PE',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_LCA_version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='waste_treatment',
            field=models.TextField(null=True),
        ),
    ]
