# Generated by Django 5.0 on 2024-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_simapro_runs_is_main_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simapro_runs',
            name='stage_A_LCA_DB',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='simapro_runs',
            name='stage_C_LCA_DB',
            field=models.TextField(null=True),
        ),
    ]
