# Generated by Django 5.0 on 2024-10-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_simapro_runs_stage_a_lca_db_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simapro_runs',
            old_name='stage_A_LCA_DB',
            new_name='Stage_A_LCA_DB',
        ),
        migrations.RenameField(
            model_name='simapro_runs',
            old_name='stage_C_LCA_DB',
            new_name='Stage_C_LCA_DB',
        ),
    ]
