# Generated by Django 5.0 on 2024-10-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_rename_stage_a_lca_db_simapro_runs_stage_a_lca_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='capex_per_ugs',
            field=models.FloatField(blank=True, db_column='capex/u.g.s.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='embodied_co2_per_ugs',
            field=models.FloatField(blank=True, db_column='embodied_co2/u.g.s.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='embodied_pe_per_ugs',
            field=models.FloatField(blank=True, db_column='embodied_pe/u.g.s.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='major_upgrade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='major_upgrade_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='opex_per_capex',
            field=models.FloatField(blank=True, db_column='opex_per_capex', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='pref_cost',
            field=models.FloatField(blank=True, db_column='Pref_cost', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='pref_env',
            field=models.FloatField(blank=True, db_column='Pref_env', null=True),
        ),
    ]
