# Generated by Django 5.0 on 2024-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_component_scale_cost_alter_component_scale_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='Stage_A_LCA_DB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='Stage_C_LCA_DB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='general_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_IA_method_GWP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_IA_method_PE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_LCA_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_A_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_IA_method_GWP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_IA_method_PE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_LCA_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='stage_C_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='waste_treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
