# Generated by Django 5.0 on 2024-10-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_simapro_runs_stage_a_lca_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='vcomponent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simapro_runs', to='inventory.component'),
        ),
    ]
