# Generated by Django 5.0 on 2024-10-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_simapro_runs_is_main_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='component_subtype',
            field=models.CharField(blank=True, db_column='subtype', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='simapro_runs',
            name='component_type',
            field=models.CharField(db_column='type', default='test_type', max_length=100),
            preserve_default=False,
        ),
    ]
