# Generated by Django 5.0 on 2024-10-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_simapro_runs_component_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_subtype',
            field=models.CharField(blank=True, db_column='subtype', max_length=250, null=True),
        ),
    ]
