# Generated by Django 5.0 on 2024-10-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_component_component_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_subtype',
            field=models.CharField(blank=True, db_column='subtype', max_length=250, null=True),
        ),
    ]
