# Generated by Django 5.0 on 2024-10-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_component_component_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simapro_runs',
            name='component_type',
            field=models.CharField(blank=True, db_column='type', max_length=100, null=True),
        ),
    ]
