# Generated by Django 5.0 on 2024-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_simapro_runs_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='thermal_properties',
            field=models.JSONField(null=True),
        ),
    ]
