# Generated by Django 5.0 on 2025-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_component_thermal_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simapro_runs_records', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('component_type', models.CharField(db_column='type', max_length=250)),
                ('component_subtype', models.CharField(blank=True, db_column='subtype', max_length=250, null=True)),
                ('capex_per_ugs', models.FloatField(blank=True, db_column='capex/u.g.s.', null=True)),
                ('opex_per_capex', models.FloatField(blank=True, db_column='opex_per_capex', null=True)),
                ('embodied_co2_per_ugs', models.FloatField(blank=True, db_column='embodied_co2/u.g.s.', null=True)),
                ('embodied_pe_per_ugs', models.FloatField(blank=True, db_column='embodied_pe/u.g.s.', null=True)),
                ('lifetime', models.FloatField()),
                ('pref_cost', models.FloatField(blank=True, db_column='Pref_cost', null=True)),
                ('pref_env', models.FloatField(blank=True, db_column='Pref_env', null=True)),
                ('scale_cost', models.FloatField(blank=True, null=True)),
                ('scale_env', models.FloatField(blank=True, null=True)),
                ('major_upgrade_point', models.FloatField(blank=True, null=True)),
                ('major_upgrade_share', models.FloatField(blank=True, null=True)),
                ('annual_performance_degradation', models.FloatField()),
                ('replace_or_die', models.CharField(max_length=250)),
                ('SHEET_TYPE', models.CharField(max_length=250, null=True)),
                ('IS_MAIN_INVENTORY', models.BooleanField(null=True)),
                ('bibliography', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thermal_properties', models.JSONField(null=True)),
                ('IS_B_COMPONENT', models.BooleanField(null=True)),
                ('eol_pe_cost', models.FloatField(blank=True, null=True)),
                ('eol_co2_cost', models.FloatField(blank=True, null=True)),
                ('simapro_version', models.CharField(blank=True, null=True)),
                ('ia_method_ghg', models.CharField(blank=True, null=True)),
                ('ia_method_pe', models.CharField(blank=True, null=True)),
                ('lca_db', models.CharField(blank=True, null=True)),
                ('functional_unit', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
